server:
  port: 8085

spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.129.179:3306/blog?characterEncoding=utf8&useSSL=false&useUnicode=true&0=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: blog
    password: simpleblog@4399

  # redis
  redis:
    # 数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #- 连接超时时间（毫秒）
    timeout: 10000
    # jedis 线程池设置
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

# mybatis
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  type-aliases-package: com.createsequence.blog.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl